### ISSUE TITLE
Add control files to Obs-Monitor

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/obs-monitor#27]
GrADS control files (`*.ctl`) contain meta data that is used in loading the legacy DA monitor data (specifically within eva).  These files are included in most, but not all of the DA monitors' extracted data.  They are inconsistent though in several key ways (file naming, level and region definitions, etc.).  Some (min and con/hist) are actually generated on-the-fly by the legacy DA monitor plotting routines and are not available in the extracted data.  In short, it's a bit of a mess. 

I'd like to add definitive copies of the control files to the Obs-Monitor package either in `obs-monitor/parm/ctl` or maybe create a new `obs-monitor/fix` for them. 

@CoryMartin-NOAA , @kevindougherty-noaa , @ADCollard do you have a preference for `obs-monitor/parm/ctl` or `obs-monitor/fix` for the control files?

**Comment by CoryMartin-NOAA** [comment]
Probably `parm` since in other repos, `fix` is usually things like binary or netCDF rather than version controlled text/YAML/etc.

**Comment by EdwardSafford-NOAA** [comment]
I'm rethinking this approach.  Among the things eva's `mon_data_space.py` gets from the control files is the assimilation flag.  For radiance data that flag does change occasionally for channels.  Additionally new instruments for radiance and ozone are added over time.  If I add the control files to `obs-monitor` then someone has to maintain them there.  If I leave things as they are then eva will continue to look to the extracted data location(s) for the control files and will get control files that match the data.

That means I'll need to re-open GSI-monitor issue 132 to update the conventional obs control files with consistent level information, and I'll add to it that MinMon and ConMon/hist needs to include control files with the data (those monitors generates them on-the-fly when needed now).

Unless there's an objection/inspiration I'm going to proceed in this direction.  @CoryMartin-NOAA @kevindougherty-noaa @ADCollard

**Comment by CoryMartin-NOAA** [comment]
Less maintenance is always a good thing. Makes sense to me.

**Comment by EdwardSafford-NOAA** [comment]
Closing this issue and will make necessary changes in GSI-Monitor [132](https://github.com/NOAA-EMC/GSI-Monitor/issues/132)

**Comment by EdwardSafford-NOAA** [comment]
After further investigation I'm re-opening this issue.  I think there is merit in including _some_ of the control files.  The MinMon and ConMon histogram control files don't contain any assimilation information and won't change.  So rather than add control files to those I'm going to add those files under a new `parm/cntrl` directory and add a {{CONTROL}} yaml substituation that resolves to it.
