### ISSUE TITLE
Implement yaml templates for GFS

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/obs-monitor#4]
Begin implementing yaml templates for current GFS/mon*.yaml files using wxflow functionality.  This will provide the mechanism to move from DA monitor templates to working yaml (e.g. customized for cycle, sat/instrument, etc) for image generation.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA I'm trying to learn my way around wxflow with mixed results.  Any idea what I need to do to preserve anchors in my input yaml file?
This line with an anchor in my input yaml file:
`levels: &levels 1,2,3,4,5` 
Becomes 
`levels: 1,2,3,4,5`  after parsing with jinga.
Is this a known issue and/or is there a known solution?

**Comment by CoryMartin-NOAA** [comment]
Hmm, is it used at all? Meaning is there a `*levels` somewhere else? I've not noticed this to be an issue before, but I haven't closely looked. Perhaps it parses and since it only finds it once it doesn't keep the anchor?

**Comment by EdwardSafford-NOAA** [comment]
My bad.  I shouldn't have panicked so quickly.  `wxflow `is doing the anchor substitutions as part of the yaml parsing.  So while I didn't expect those changes, the output file still works as intended with eva.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA  I've found an order of operations problem with the !INC mechanism that I haven't been able to resolve.  I'd like to put things like levels and channels in separate files because they are specific to each sat/sensor.  If they are in separate files, a simple naming convention would allow for easy substitution and loading.

But that's not working.  If I put `&levels 1,2,3,4,5` in an external file and load it using `levels: !INC my_file.yaml` I get an error that the alias resolution of `*levels`  has failed because levels is not defined.  If I just load the external file and call it something that isn't used in my yaml plot file, say `levs: !INC my_file.yaml`  the included file is loaded, minus the ampersand, and is in my out.yaml file.  So I can load it but only if I don't use it.

I can get around that if I put the levels info into a file that I read from my version of genYAML.  If I load the levels into the config dictionary as `config['LEVELS'] = &levels 1,2,3,4,5` and in my plot.yaml file use `levels: {{LEVELS}}`  the replacement works before the alias resolution.  

Is this order of operations a known issue?  And, am I missing something obvious?

**Comment by CoryMartin-NOAA** [comment]
Hmm, I think you're encountering a case we haven't yet dealt with, and I think it may be a problem as it is currently set up. The workflow/JEDI YAMLs I've seen so far have tended to only use the anchors/aliases within an individual YAML and not across them.

What I think we want to do is basically what you listed at the end, where LEVELS is defined earlier before the include mechanism.

In fact, if you do the `{{LEVELS}}' approach, there's no need for the `&levels` and `*levels`, right? I think so, since each location would be replaced with `{{LEVELS}}'. The `&*` syntax is YAML specific and probably is intended for only one YAML, since we are doing fancy Jinja templating and parsing, we might not be able to use that syntax.

**Comment by EdwardSafford-NOAA** [comment]
Yes, you're correct -- with the jinga substitution we don't need to use the anchor/alias method.  I hadn't gotten there yet, thanks.

My idea at the moment is to build a dictionary of sats/sensors.  Each sat/sensor combination will have levels|channels, plot types, and times.  My genYaml equivalent will loop through the dictionary and load levels|channels, times, sat, and sensor into the config, generate the yaml via jinga, and then run the result through eva.  Presto!  That would cover Rad and Ozn plots.  The MinMon and Conv plots would be a little bit different but I think they could be made to fit in that structure.

**Comment by CoryMartin-NOAA** [comment]
Sounds like a good plan to me!

**Comment by EdwardSafford-NOAA** [comment]
Closed with PR #5
